name: Deploy Docs to Pages

on:
  push:
    branches: [ "main" ]
    paths:
      - docs/**

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v2
    
      - name: Install Dependencies
        working-directory: ./docs
        run: npm install

      - name: Build ddoc
        working-directory: ./docs
        uses: dlang-community/setup-dlang@4c99aa991ce7d19dd3064de0a4f2f6b2f152e2d7
        run: ./build-ddoc.d
        
      - name: Build Static HTML Site
        working-directory: ./docs
        run: npm run build
        
      - name: Upload to Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./docs/src/.vuepress/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1