name: Integration Tests

on:
  push:
    branches: [ "main" ]
    paths:
      - source/**
      - integration-tests/**
      - .github/workflows/integration-tests.yml
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  integration-tests:
    name: Integration Tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        compiler: [dmd-2.099.1, dmd-latest, ldc-1.31.0]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.compiler }}
      
      - name: Run speed-test
        working-directory: integration-tests/speed-test
        run: dub -q run
