name: Unit Tests

on:
  push:
    branches: [ "main" ]
    paths:
      - source/**
      - .github/workflows/unit-tests.yml
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    name: Dub Tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        compiler: [dmd-2.099.1, dmd-latest, ldc-1.31.0]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.compiler }}

      - name: 'Build & Test'
        run: |
          # Build the project, with its main file included, without unittests
          dub -q build
          # Build and run tests, as defined by `unittest` configuration
          # In this mode, `mainSourceFile` is excluded and `version (unittest)` are included
          # See https://dub.pm/package-format-json.html#configurations
          dub -q test
